### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/frankenstein#1]
# road to 1.0
:cold_sweat:

- white list https://stackoverflow.com/questions/ask?tags=realm - redirects to 
https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=https%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3drealm 
- http://groups.google.com/group/ruby-bundler redirects to http://groups.google.com/forum/%23!forum/ruby-bundler 

# :runner: `pull`
- [ ] iCHAIT/awesome-osx
- [x] bbatsov/ruby-style-guide  
- [x] guard/guard
- [ ] kylef/Spectre 
- [ ] bbatsov/rubocop

## issues
- [ ] redirect issues https://github.com/Conche/Conche/pull/18
- [ ] shields.io detect if it says `build invalid` 
- [ ] travis looks for https://travis-ci.org/kylef/fakerepoyo `The repository at kylef/fakerepoyo was not found.`
- [x] option `r` overlaps with `threads`
- [ ] greedy subsitution issue https://github.com/fastlane/boarding/pull/28/files .. do substitution starting with longest.. ?

## test
- [ ] test `repo` option: `frankenstein dkhamsing/travis-playground -r pull`
- [ ] test pull ??
- [x] white list
- [x] add more tests

## misc
- [ ] pull to enter additional info in description
- [ ] pull request description to include 4xx
- [ ] prevent pull request spamming
- [ ] errors when using wrong options, flags
- [ ] make modules :exclamation: 
- [ ] remove option row :cry: 
- [x] isolate network code
- [ ] isolate github code
- [ ] have a list of branch_variants ?
- [ ] update so that cli -flags can be in any position
- [ ] error if trying to do pull request without repo
- [ ] pull request should create a branch?
- [ ] pull request to work if not master
- [ ] `stars` and `g` would not work on travis..
- [ ] if/when promoting to master, update `osia` and Travis-playground yml
- [ ] make head requests ? find issues for https://developer.apple.com/sample-code/wwdc/2015/ or some redirects..

dkhamsing/open-source-ios-apps 
```
📋  frankenstein results: 4 issues (1%)
   (4 of 358 links)
🔴  401 https://developer.apple.com/library/prerelease/ios/samplecode/Lister/Introduction/Intro.html
🔶  301 http://www.appcoda.com/instagram-app-parse-swift
🔴  401 https://developer.apple.com/library/ios/navigation/#section=Resource%20Types&topic=Sample%20Code
🔴  401 https://developer.apple.com/sample-code/wwdc/2015/

🔶  1 redirect
http://www.appcoda.com/instagram-app-parse-swift redirects to 
http://www.appcoda.com/instagram-app-parse-swift/ 
```
 
## ?
- [ ] use https://github.com/commander-rb/commander ?
- [ ] use this for parallels ? https://github.com/lostisland/faraday/wiki/Parallel-requests
- [ ]  make it so that it can run by typing frankenstein instead of ./frankenstein ? http://unix.stackexchange.com/a/162137
- [x] write log to root dir?
- [ ]  publish gem? http://guides.rubygems.org/publishing/

## finish
- [ ] delete travis branch
- [ ] redo demo
- [ ] update readme example (parallel) 
- [ ] r----e :grin: 

available options `c b i j k n q x y `

taken `logpullreporowrepothreads = lopurerwthads + fzmv`

demo script
``` 
frankenstein
frankenstein dkhamsing/DKImageBrowser
frankenstein https://fastlane.tools -fm
```

## done
- [x] use constants in usage
- [x] update usage with `update/push` option
- [x]  github last updated date
- [x] star count diff
- [x] Do not replace white listed items
- [x] franken_json entries should be updated 
- [x]  maybe travis should not be redirected
- [x] when finding default branch.. use it for `pull` option: try it with https://github.com/dkhamsing/travis-playground which has a default `test` branch
- [x] function to parse option with = separator
- [x] update output to find branch before output log
- [x] use found branch for pull request
- [x] use rubocop
- [x] handle 500 errors http://dkhamsing.tumblr.com
- [x] change `pull` to prompt for pull request
- [x] find default branch without octokit
- [x] find default branch of a repo i.e. `frankenstein dkhamsing/frankenstein`
- [x] rename option log to `log` again - need to rename option g?
- [x] try 1.0wip in travis-playground
- [x] bug: log and thread requir s netrc?? Option g conflicts with log: rename log to `lo`
- [x]  show frankenbot's work in readme 
- [x] bundle install in readme 
- [x] update usage and readme, `row=d` only works with `threads=0`
- [x] put pull request title and description in a constant
- [x] integrate with Travis 
- [x]   move status gauge below first example 
- [x]  creating pull request text should be ... + update readme example 
- [x] update credits (mattgreensmith, stackoverflow)
- [x] output is now out of order with `parallel`.. Disable counter if threads > 0
- [x] writing files breaks travis (redirect)
- [x] can create a pull request to fix redirects
- [x] update demo
- [x] find where 300s redirect to
- [x] crashes for enaqx/awesome-react https://usepropeller.com/blog/posts/from-backbone-to-react/
- [x] modularize 
- [x] better error when readme not found (in master)
- [x] white list travis ci svg, creative commons png ?
- [x] redo demo, script: dk image browser then fast lane with options fm
- [x] error if missing github creds
- [x] pass argument `log_number_of_items_per_row`
- [x] use https://github.com/defunkt/colored
- [x] rename g-only option
- [x] show result in readme 
- [x] write gh stars to franken log
- [x] pass arg `log_to_file` 
- [x] debug duration minutes missing seconds?
- [x] github stars only
- [x] readme setup octokit user pass
- [x] repos should be unique
- [x] filtered should be unique
- [x] errors for http://google.com
- [x] errors for http://github.com
- [x] run duration in results
- [x]  look for variation of repo readme using faraday
- [x] remove use of open uri from code and readme 
- [x] note about the glyphs
- [x]  case where there is one link
- [x]  redo demo
- [x]  look at https://github.com/KrauseFx/deliver to structure code
- [x] integrate with osia
- [x] input local file
- [x] add a note on travis usage 

.travis.yml

```
language: ruby
rvm:
  - 2.2
before_script:
  - wget https://github.com/dkhamsing/frankenstein/archive/1.0-wip.tar.gz -O /tmp/frankenstein.tar.gz
  - tar -xvf /tmp/frankenstein.tar.gz
  - export PATH=$PATH:$PWD/frankenstein-1.0-wip/bin/
  - cd frankenstein-1.0-wip
  - bundle install
script:  
  - frankenstein ../README.md
```

example: https://travis-ci.org/dkhamsing/open-source-ios-apps/builds/87744055

**Comment by e2** [comment]
Yeah, Google Groups link is broken: https://groups.google.com/forum/%23!forum/guard-dev

**Comment by dkhamsing** [comment]
Thanks @e2
