### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/frankenstein#14]
Close this pull!
R---a-e
Delete Travis branch 

- automate update of travis.yml .. ??? https://github.com/rshipp/awesome-malware-analysis/pulls `39`
- visit  add language
- ignore white list 
- rename to readmecritic
- https://github.com/mivok/markdownlint
- ~~change Travis to rake install~~
- put more information in visits json .. Readme?
- review / pull should check that readme is still unchanged 
- remove option silent 
- [ ] isolate / split up cli
- [ ] if a wrong item is in todo, could fail i.e. `@usernakjdlaljdla/dajsljdlka` 
- [ ] sync `visits.json` across computers
- [ ] backup json visits :cry: 
- [ ] fork should check if fork exists
- [ ] cron job for `new` ?
- [ ] update demo
- [ ]  frankensten should use visits.json when reporting previous runs
- [ ] split github and github_json
- [ ] isolate getting readme name and url 
- [ ] correct urls format: separate when only change is www
- [ ] add validation to `todo`
- [ ] automate `issues o`
- [ ] isolate get github repos for user
- [ ] process issues should not work on issues belonging to someone else
- [ ] run issue close to include summary of redirects
- [ ] scan most active users https://github.com/paulmillr/top-github-users
- [ ] readmecritic/run to support username
- [ ] update run readme ^
- [ ] add search to `review logs` 
- [ ] review single project should prompt to open pull in safari (pass an option to skip prompt for `scan`)
- [ ] website where user auths and run with their creds
- [ ] scan links on a page.. has to use a web page renderer
- [ ] use progress bar, there are issues though https://github.com/dkhamsing/frankenstein/tree/progress-bar
- [ ] twitter creds
- [ ] next action based on .netrc permission
- [ ] fix log processing regex for `announce` 
- [ ] help wanted issue?
- [ ] use pry
- [ ] fix rubocop
- [ ] travis: how to not install dev dependencies like `guard-rubocop`
- [ ] diff log should show date interval
- [ ] pull to enter additional info in description
- [ ] pull request description to include 4xx
- [ ] prevent pull request spamming
- [ ] errors when using wrong options, flags
- [ ] make modules :exclamation: 
- [ ] update so that cli -flags can be in any position
- [ ] `stars` and `z` would not work on travis..
- [ ] if/when promoting to master, update `osia` and Travis-playground yml
- [ ] make head requests ? find issues for https://developer.apple.com/sample-code/wwdc/2015/ or some redirects..

frankenstein dkhamsing/open-source-ios-apps  head
```
📋  frankenstein results: 4 issues (1%)
   (4 of 379 links
🔴  401 https://developer.apple.com/library/prerelease/ios/samplecode/Lister/Introduction/Intro.html
⚪  501 https://telegram.org/apps
🔴  401 https://developer.apple.com/library/ios/navigation/#section=Resource%20Types&topic=Sample%20Code
🔴  401 https://developer.apple.com/sample-code/wwdc/2015/
```

## test
- [ ] test `repo` option: `frankenstein dkhamsing/travis-playground head`
- [ ] test pull ??

## ?
- [ ] checkout https://github.com/CocoaPods/CLAide
- [ ] pull request should create a branch?
- [ ] use https://github.com/commander-rb/commander ?
- [ ] use this for parallels ? https://github.com/lostisland/faraday/wiki/Parallel-requests
- [ ]  make it so that it can run by typing frankenstein instead of ./frankenstein ? http://unix.stackexchange.com/a/162137 `export PATH=$PATH:.`

``` 
install :
	sudo cp app-name /usr/local/bin/
```

## finish
- [ ] delete travis branch
- [ ] redo demo
- [ ] r----e :grin: 
- [ ] oops this should go into `master` :cry: 

demo script - convert settings `okay & small`
``` 
frankenstein
frankenstein dkhamsing/DKImageBrowser
frankenstein https://fastlane.tools -fm
```
